### ISSUE TITLE
Data management for LANDFIRE tiffs

### ISSUE THREAD

**Issue by esgeo** [AreteY/post-wildfire-recovery#18]
Was planning on writing code that just crops the data to the fire perimeter, but I have already downloaded the dataset that covers CONUS and thus is very large. Need to look into whether one can request a subset of LANDFIRE data based on geographic bounds and avoid downloading several GB size datasets for the workflow

**Comment by Chathu84** [comment]
You could subset with this tool right? Draw the polygon where you want the data and navigate through "Data download tool" to open and select the layers you want to download. Let me know if that works.

https://landfire.gov/viewer/

**Comment by esgeo** [comment]
> @esgeo You could subset with this tool right? Draw the polygon where you want the data and navigate through "Data download tool" to open and select the layers you want to download. Let me know if that works.
> 
> https://landfire.gov/viewer/
> 
> The other option is trying GEE. There are some products in GEE but not sure it has all you want.

@Chathu84 Thank you Nayani. I've tinkered with the web-based polygon GUI and it seems to just hang up on me using multiple computers. However, I've found RESTful API method that might work a little easier. Will try to get this done ASAP.

https://lfps.usgs.gov/helpdocs/LFProductsServiceUserGuide.pdf
