### ISSUE TITLE
Evaluate field data for NEON GRSM site

### ISSUE THREAD

**Issue by AreteY** [AreteY/post-wildfire-recovery#3]
Look at pre- and post-Chimney Tops 2 fire vegetation type and cover for Great Smoky Mountains National Park.

**Comment by AreteY** [comment]
Hi @Chathu84 - I've downloaded the shapefiles for all of the NEON Terrestrial Observation Plots and plotted them within the fire boundary. My next step is to determine which tiles overlap with the plots.

**Comment by Chathu84** [comment]
Hi @AreteY Yes, That is great. Then we can extract spectral signatures from those plots (for trees and other veg classes if NEON have specifically collected information on) to build our library.

**Comment by AreteY** [comment]
Hi @Chathu84  I've confirmed that the same TOS plots are reviewed in 2016 (pre-fire) and 2017 (post-fire). There are 10 TOS plots within the fire perimeter that are in 9 tiles. The field data classify for NLCD class, scientific name (lowest taxonomic rank), and scientific family. Which classification should we use? Also should I get the pixel spectra from the dNBR spectra?

**Comment by AreteY** [comment]
Hi @Chathu84 I've looked at the plots again and found that for each plot ID, there are 8 subplots that are 1-m^2 and we can get the coords for these subplots using the API. It's strange when you look at the percent cover for the 'otherVariables' (non-vegetation), the total percent cover is usually around 99. But the sum of the vegetation (vegetation entries that are assigned a family) is a smaller number. For example, for plot 55, the sum of the vegetation percent cover varies from 13.5 to 34.5 for the different subplots. Does this mean, for example, that we can say for subplot 40.1.1, that the total vegetation is 13.5% and the rest 86.5% is non-vegetation (and we know the partitioning by the otherVariables column)? Does this seem reasonable?

**Comment by Chathu84** [comment]
Hi @AreteY Yes, for that subplot, 13.5% is the veg percentage and the rest is the others. It's great we have more subplots (within big plots) and have their coordinates.

**Comment by AreteY** [comment]
Closing field data issue #3
